nombre= input("Ingrese nombre: ")
boleta= input("Ingrese numero de boleta: ")
print("Ingresar calificaciones")
cal1= float(input("cal1="))
cal2= float(input("cal2="))
cal3= float(input("cal3="))
cal4= float(input("cal4="))
cal5= float(input("cal5="))
prom=(cal1+cal2+cal3+cal4+cal5)/5
print("El alumno con nombre: ", nombre," ,con boleta: ", boleta, ", su promedio es de: ", prom)