print("Ingrese precio de venta por unidad")
precio_de_venta= float(input())
print("Ingrese cantidad vendida")
cantidad= int(input())
print("Ingrese el costo fijo")
costo_fijo= float(input())
print("Ingrese el costo variabe por pieza")
costo_variable= float(input())
beneficio= (precio_de_venta*cantidad)-(costo_fijo+(costo_variable*cantidad))
print("beneficio es:", beneficio)