hrs_extras= float(input("Ingresar horas extras trabajadas: "))
pago_hrs=int(63)
print("Pago por hora es: ", pago_hrs)
hrs_sem= int(40)
print("Horas que se trabajan a la semana: ", hrs_sem)
pago_hrs_extra= int(80)
print("El pago por horas extras es: ", pago_hrs_extra)
salario_semanal= (pago_hrs*hrs_sem)
print("salario semanal es: ", salario_semanal)
salario_hrs_extra= (salario_semanal)+(hrs_extras*pago_hrs_extra)
print("El salario con horas extras es: ", salario_hrs_extra)